"""initial

Revision ID: 19fd7781d00f
Revises: 
Create Date: 2026-05-03 01:47:02.745784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '19fd7781d00f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: pgvector extension requires compilation for PostgreSQL 15
    # Temporarily skip vector extension and embedding column
    # To enable later: brew install pgvector (for PG15) and uncomment below
    # op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('CHAT', 'TASK', 'ANALYSIS', 'ORCHESTRATOR', 'CUSTOM', name='agenttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'ERROR', name='agentstatus'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.String(length=10), nullable=True),
    sa.Column('max_tokens', sa.String(length=10), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agents_created_at', 'agents', ['created_at'], unique=False)
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=True)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_index(op.f('ix_agents_type'), 'agents', ['type'], unique=False)
    op.create_index('ix_agents_type_status', 'agents', ['type', 'status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('doc_metadata', sa.JSON(), nullable=False),
    # sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True),  # Temporarily disabled - requires pgvector for PG15
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('parent_document_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_created_at', 'documents', ['created_at'], unique=False)
    # op.create_index('ix_documents_embedding', 'documents', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})  # Temporarily disabled - requires pgvector
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index('ix_documents_parent_id', 'documents', ['parent_document_id'], unique=False)
    op.create_index('ix_documents_source', 'documents', ['source'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('execution_type', sa.Enum('SEQUENTIAL', 'PARALLEL', 'CONDITIONAL', 'GRAPH', name='executiontype'), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED', name='workflowstatus'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('timeout', sa.String(length=10), nullable=True),
    sa.Column('retry_policy', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflows_created_at', 'workflows', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflows_execution_type'), 'workflows', ['execution_type'], unique=False)
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_name'), 'workflows', ['name'], unique=False)
    op.create_index(op.f('ix_workflows_status'), 'workflows', ['status'], unique=False)
    op.create_index('ix_workflows_status_type', 'workflows', ['status', 'execution_type'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('conv_metadata', sa.JSON(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_agent_id', 'conversations', ['agent_id'], unique=False)
    op.create_index('ix_conversations_created_at', 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'TIMEOUT', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_agent_id'), 'tasks', ['agent_id'], unique=False)
    op.create_index('ix_tasks_agent_status', 'tasks', ['agent_id', 'status'], unique=False)
    op.create_index('ix_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_status_priority', 'tasks', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_tasks_workflow_id'), 'tasks', ['workflow_id'], unique=False)
    op.create_index('ix_tasks_workflow_status', 'tasks', ['workflow_id', 'status'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('execution_type', sa.String(length=50), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('STARTED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='executionstatus'), nullable=False),
    sa.Column('exec_metadata', sa.JSON(), nullable=False),
    sa.Column('logs', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_agent_id'), 'executions', ['agent_id'], unique=False)
    op.create_index('ix_executions_agent_status', 'executions', ['agent_id', 'status'], unique=False)
    op.create_index('ix_executions_created_at', 'executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_executions_id'), 'executions', ['id'], unique=False)
    op.create_index(op.f('ix_executions_status'), 'executions', ['status'], unique=False)
    op.create_index(op.f('ix_executions_task_id'), 'executions', ['task_id'], unique=False)
    op.create_index('ix_executions_task_status', 'executions', ['task_id', 'status'], unique=False)
    op.create_index('ix_executions_type_status', 'executions', ['execution_type', 'status'], unique=False)
    op.create_index(op.f('ix_executions_workflow_id'), 'executions', ['workflow_id'], unique=False)
    op.create_index('ix_executions_workflow_status', 'executions', ['workflow_id', 'status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('msg_metadata', sa.JSON(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index('ix_messages_role', 'messages', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_role', table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_executions_workflow_status', table_name='executions')
    op.drop_index(op.f('ix_executions_workflow_id'), table_name='executions')
    op.drop_index('ix_executions_type_status', table_name='executions')
    op.drop_index('ix_executions_task_status', table_name='executions')
    op.drop_index(op.f('ix_executions_task_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_status'), table_name='executions')
    op.drop_index(op.f('ix_executions_id'), table_name='executions')
    op.drop_index('ix_executions_created_at', table_name='executions')
    op.drop_index('ix_executions_agent_status', table_name='executions')
    op.drop_index(op.f('ix_executions_agent_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index('ix_tasks_workflow_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_workflow_id'), table_name='tasks')
    op.drop_index('ix_tasks_status_priority', table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index('ix_tasks_created_at', table_name='tasks')
    op.drop_index('ix_tasks_agent_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_agent_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index('ix_conversations_created_at', table_name='conversations')
    op.drop_index('ix_conversations_agent_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_workflows_status_type', table_name='workflows')
    op.drop_index(op.f('ix_workflows_status'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_name'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_execution_type'), table_name='workflows')
    op.drop_index('ix_workflows_created_at', table_name='workflows')
    op.drop_table('workflows')
    op.drop_index('ix_documents_source', table_name='documents')
    op.drop_index('ix_documents_parent_id', table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index('ix_documents_embedding', table_name='documents', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_documents_created_at', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_agents_type_status', table_name='agents')
    op.drop_index(op.f('ix_agents_type'), table_name='agents')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_index('ix_agents_created_at', table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
