"""integration packages

Revision ID: 680cd033bf05
Revises: 0057_canned_replies
Create Date: 2026-09-05 14:54:07.490194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '680cd033bf05'
down_revision: Union[str, None] = '0057_canned_replies'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connection_template', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_packages_is_active'), 'integration_packages', ['is_active'], unique=False)
    op.create_index(op.f('ix_integration_packages_slug'), 'integration_packages', ['slug'], unique=True)
    op.create_table('integration_package_tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('risk_classification', sa.String(length=20), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_template', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('record_path', sa.String(length=500), nullable=False),
    sa.Column('max_records', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['integration_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_package_tools_package_id'), 'integration_package_tools', ['package_id'], unique=False)
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_package_tools_package_id'), table_name='integration_package_tools')
    op.drop_table('integration_package_tools')
    op.drop_index(op.f('ix_integration_packages_slug'), table_name='integration_packages')
    op.drop_index(op.f('ix_integration_packages_is_active'), table_name='integration_packages')
    op.drop_table('integration_packages')
    # ### end Alembic commands ###
