"""Internal contracts shared by data source execution services."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any
from uuid import UUID


@dataclass(frozen=True, slots=True)
class ToolConfig:
    """Complete, framework-independent configuration for one callable tool."""

    name: str
    method: str
    path: str
    input_schema: dict[str, Any]
    request_template: dict[str, Any] = field(default_factory=dict)
    record_path: str = ""
    field_mapping: dict[str, str] = field(default_factory=dict)
    max_records: int = 20
    max_response_bytes: int = 1_000_000
    risk_classification: str = "read"
    base_url: str = ""
    default_headers: dict[str, str] = field(default_factory=dict)
    auth_type: str = "none"
    auth_header: str | None = None
    encrypted_secret: str | None = None


@dataclass(frozen=True, slots=True)
class ExecutionContext:
    """Trusted application context for an execution.

    These identifiers are supplied by the authenticated runtime, never by tool
    arguments generated by a model.
    """

    space_id: UUID | str
    chatbot_id: UUID | str
    request_id: str | None = None


@dataclass(frozen=True, slots=True)
class ExecutionFailure:
    """Stable, safe failure information suitable for model-facing results."""

    code: str
    message: str
    retryable: bool = False
    status_code: int | None = None


@dataclass(frozen=True, slots=True)
class ExecutionResult:
    """Bounded structured output from a data source tool call."""

    records: list[dict[str, Any]] = field(default_factory=list)
    status_code: int | None = None
    latency_ms: int | None = None
    failure: ExecutionFailure | None = None

    @property
    def succeeded(self) -> bool:
        return self.failure is None


@dataclass(frozen=True, slots=True)
class DraftConnection:
    name: str
    base_url: str
    auth_type: str = "none"
    auth_header: str = "Authorization"
    credential_required: bool = False
    default_headers: dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class DraftTool:
    name: str
    display_name: str
    description: str
    method: str
    path: str
    input_schema: dict[str, Any]
    request_template: dict[str, Any] = field(default_factory=dict)
    record_path: str = ""
    output_mapping: dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class DataSourceDraft:
    source_type: str
    connection: DraftConnection
    tool: DraftTool
    warnings: tuple[str, ...] = ()
